### ISSUE TITLE
[BUG]: Binary classification 

### ISSUE THREAD

**Issue by prashanthharshangi** [scikit-learn-contrib/MAPIE#109]
**Describe the bug**
Assertion error: For binary classification problems with `y in [0, 1]` 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
https://github.com/scikit-learn-contrib/MAPIE/blob/master/mapie/classification.py#L513

`assert type_of_target(y) in ["binary", "multiclass"]`

**Comment by gmartinonQM** [comment]
Hi @prashanthharshangi , this is not a bug, MAPIE only deals with multi-class classification for now, because the very notion of prediction set does not make sense in the binary case. In the binary case, look for calibration : https://scikit-learn.org/stable/modules/calibration.html

**Comment by e-pet** [comment]
Hi @gmartinonQM! I am slightly confused by your response. :-) What I would be interested in, and what I would imagine @prashanthharshangi might also have been looking for, are confidence intervals for the risk scores returned by a binary classifier. I.e., the classifier might return a risk score of .76, but there is also uncertainty associated with that risk score. Many people are interested in uncertainty quantification for such risk scores (see, e.g., [here ](https://www.nature.com/articles/s41588-021-00961-5 ) and [here](https://bmcmedicine.biomedcentral.com/articles/10.1186/s12916-019-1368-8)), and this is an issue that is fully separate from calibration.

Could mapie also be used for that problem? (Binary) risk score estimation is basically single-variable regression, so I would image it should be possible, at least in theory?

**Comment by gmartinonQM** [comment]
Hi @e-pet , in this paper : https://arxiv.org/pdf/2006.10564.pdf , section 2.2, you can see that there is an impossibility theorem for getting mathematical guarantees about confidence intervals in the binary case. This is why the notion of calibration is the most relevant to begin with for binary classification.

In theorem 4 of the same paper however, you can indeed go further and get confidence interval around a _calibrated_ score provided you discretize it. There is thus a trade-off between bin size and statistical significance of your interval. This is something we have not prioritized yet, but could indeed be useful in MAPIE the future : calibrating + discretizing + getting confidence intervals on dicretized, calibrated scores.

**Comment by e-pet** [comment]
Thanks for the pointer @gmartinonQM; really interesting paper! I'll be honest though, I am having trouble intuitively understanding why exactly probability regression should be inherently "harder" than any other kind of regression? Can you help me understand this / gain an intuition?
