### ISSUE TITLE
[ENHANCEMENT]: MAPIE is not available for Time Series yet

### ISSUE THREAD

**Issue by tmorzade** [scikit-learn-contrib/MAPIE#134]
**Is your feature request related to a problem? Please describe.**
MAPIE has not yet a dedicated method for time series regression.

**Describe the solution you'd like**
A valid method for time series.

**Comment by Kevin-Chen0** [comment]
Hi @tmorzade, just wanted a follow-up on this since I'm also very interested in the time-series regression feature. Or whether you need any help. Thanks!

**Comment by tmorzade** [comment]
Hi @Kevin-Chen0 
I will do my best to finish this EnbPI PR this week. I hope the release will be done next Friday

**Comment by Kevin-Chen0** [comment]
Thanks! Looking forward to it.
