### ISSUE TITLE
[ENHANCEMENT] Provide new residual scores for regression

### ISSUE THREAD

**Issue by kapytaine** [scikit-learn-contrib/MAPIE#141]
**Problem description**
Currently, the regression confidence intervals are based on the absolute value of the residuals `self.residuals_ = np.abs(np.ravel(y) - y_pred)`. From my experience, in some cases, this may not be appropriate, for two main reasons:
- We expect the confidence interval not to be symmetrical around the predicted value.
- We expect the confidence interval to be conditioned (scaled for instance) on the predicted value.

I ended up with these conclusions by applying MAPIE to a [house price dataset from kaggle](https://www.kaggle.com/shivachandel/kc-house-data). My initial hunch was that the confidence intervals should scale with the predicted value. For instance, I would prefer to get the two following house prices 100 k€ +/- 10 k€ and 1000 k€ +/- 100 k€ instead of 100 k€ +/- 10 k€ and 1000 k€ +/- 10 k€.

**Describe the solution you'd like**
I suggest to add an argument in the `fit` method of `MapieRegressor` class. The argument would be an instance of a class (that I chose to name ResidualScore). The confidence intervals would then be conditioned on the residual scores (I prefer to call them "scores" instead of "residuals" since they may not simply be `np.ravel(y) - y_pred` which is the definition of residuals if I am correct). Different inherited classes may be created from ResidualScore. For instance I wrote the class AbsoluteResidualScore which gives the same results as currently and the class GammaResidualScore which computes the residual scores by (y - y_pred) / y_pred. 

**Illustrations**
I have tested the proposed approach on the house price dataset. The two figures depict the predicted values with their confidence intervals based on the absolute value of the residuals (on the left) and on the proposed gamma residual score (on the right).
![comparison_AbsoluteResidualScore_GammaResidualScore](https://user-images.githubusercontent.com/77614412/158984707-591ef91e-4e76-4922-a055-f60c880d84ec.png)

**NB**
I know that the quantile regression may be a solution to meet my expectations regarding this particular problem. I do not know if my proposal could be another tool to address such problems or if quantile regression should/must be prioritized.

**Comment by gmartinonQM** [comment]
Hi @kapytaine, feel free to start a PR about this interesting subject ! Do not hesitate to organize your PR into small independent parts, make the PRs as small as possible, in order to get feedbacks as soon as possible.

**Comment by nilslacroix** [comment]
Interesting, ist there any theoretical background about this gamma scoring? Did not find anything so far.

**Comment by kapytaine** [comment]
The short answer is no. Anyway, I will try to first give you the reasons why I thought about this and secondly my analysis of the theoretical proof.

## My intuition
I first came to this proposal by considering two regression models, one assuming that the target follows a Normal distribution with parametrized means and common variance:
<p align="center"><img src="https://render.githubusercontent.com/render/math?math={\forall{i}: Y_i \sim \mathcal{N}(\mu(X_i), \sigma^{2})}"></p>
And one assuming that the target follows a Gamma distribution with parametrized means, variances and common ratio variance over squared mean:
<p align="center"><img src="https://render.githubusercontent.com/render/math?math={\forall{i}: Y_i \sim \Gamma(\alpha, \beta_i)}"></p>
<p align="center"><img src="https://render.githubusercontent.com/render/math?math={ \mu(X_i)=\frac{\alpha}{\beta_i} }"></p>
In both cases, we can find another random variable which distribution is independent on i. First for the Normal distribution:
<p align="center"><img src="https://render.githubusercontent.com/render/math?math={ \forall{i}: Y_i - \mu(X_i)\sim \mathcal{N}(0, \sigma^{2}) }"></p>
An then for the Gamma distribution:
<p align="center"><img src="https://render.githubusercontent.com/render/math?math={ \forall{i}: \frac{Y_i}{\mu(X_i)} \sim \Gamma(\alpha, \beta_i\mu(X_i))=\Gamma(\alpha,\alpha) }"></p>
Finally, this last random variable can be shifted so that it has 0 mean:
<p align="center"><img src="https://render.githubusercontent.com/render/math?math={ \frac{Y_i}{\mu(X_i)}-1 }"></p>

In practice, we don't have access to the true μ, however, I drew my inspiration from the previous results to propose the following residual score <img src="https://render.githubusercontent.com/render/math?math={ \frac{Y_i}{\hat{\mu}(X_i)}-1 }"> (what I name Gamma residual score) instead of <img src="https://render.githubusercontent.com/render/math?math={ |Y_i - \hat{\mu}(X_i)| }"> (which I name absolute Normal residual score). Since the Gamma distribution is asymmetrical, I did not add the absolute function.

## My theoretical analysis
I know that there is a theorem to build [the jackknife+ prediction interval](https://arxiv.org/pdf/1905.02928.pdf). I tried to adjust it for my case. I hope I didn't make any mistake. If so, please let me know.

### R matrix construction
Instead of defining the R matrix with the absolute residual (absolute Normal residual score if I stick to my naming) like in the paper, I assume that R is defined with other metrics. For instance the Gamma residual score:
<p align="center"><img src="https://render.githubusercontent.com/render/math?math={ R_{i,j} = \frac{Y_{i}}{\hat{\mu}_{-(i,j)}(X_{i})}-1 }"></p>
<p align="center"><img src="https://render.githubusercontent.com/render/math?math={ R_{i}^{LOO} = R_{i,n%2B1} }"></p>

### Strange points
Instead of the single <img src="https://render.githubusercontent.com/render/math?math={ S(A) }"> set, I think that two cases should be considered, <img src="https://render.githubusercontent.com/render/math?math={ S_{%2B}(A)=\{i \in \{1,...,n%2B1\}:A_{i.}\geq(1-\frac{\alpha}{2})(n%2B1)\} }"> for "data points with unusually large [positive] residuals", and <img src="https://render.githubusercontent.com/render/math?math={ S_{-}(A)=\{i \in \{1,...,n%2B1\}:(n-A_{i.})\geq(1-\frac{\alpha}{2})(n%2B1)\} }"> for "data points with unusually large [negative] residuals" (or consider <img src="https://render.githubusercontent.com/render/math?math={ A_{-}=J-A }"> for the second set: <img src="https://render.githubusercontent.com/render/math?math={ S_{-}(A)=S_{%2B}(A_{-}) }">, with J being a matrix of ones).

### Step 1 and 2 are unchanged
Changing the R, does not change the results of the steps 1 and 2. From step 1, we have that <img src="https://render.githubusercontent.com/render/math?math={ |S_{%2B}(A)| \leq \alpha (n%2B1) }"> and <img src="https://render.githubusercontent.com/render/math?math={ |S_{-}(A)| \leq \alpha (n%2B1) }">. From step 2, we have that the probability of the test point n+1 being strange inside <img src="https://render.githubusercontent.com/render/math?math={ S_{%2B}(A) }"> is bounded by α and the probability of the test point n+1 being strange inside <img src="https://render.githubusercontent.com/render/math?math={ S_{-}(A) }"> is also bounded by α.

### Step 3
Similarly to the theorem proof, let's suppose that <img src="https://render.githubusercontent.com/render/math?math={ Y_{n%2B1} \notin \hat{C}_{n,\alpha}^{jackknife%2B}(X_{n%2B1}) }">. This means either:
<p align="center"><img src="https://render.githubusercontent.com/render/math?math={ Y_{n%2B1}>\hat{q}_{n,\frac{\alpha}{2}}^{%2B}\{\hat{\mu}_{-i}(X_{n%2B1})(1%2BR_{i}^{LOO})\} }"></p>
which implies that:
<p align="center"><img src="https://render.githubusercontent.com/render/math?math={ Y_{n%2B1} > \hat{\mu}_{-j}(X_{n%2B1})(1%2BR_{j}^{LOO}) }"></p> for at least α/2(n+1) many indices j ∈ {1,...,n}, or otherwise:
<p align="center"><img src="https://render.githubusercontent.com/render/math?math={ Y_{n%2B1}<\hat{q}_{n,\frac{\alpha}{2}}^{-}\{\hat{\mu}_{-i}(X_{n%2B1})(1%2BR_{i}^{LOO})\}}"></p>
which implies that 
<p align="center"><img src="https://render.githubusercontent.com/render/math?math={ Y_{n%2B1} < \hat{\mu}_{-j}(X_{n%2B1})(1%2BR_{j}^{LOO}) }"></p>
for at least α/2(n+1) many indices j ∈ {1,...,n}.

Here <img src="https://render.githubusercontent.com/render/math?math={ R_{j}^{LOO} }"> is signed (it can be positive or negative) so it is added (+) in both cases. Besides, α/2 is used instead of α since to get the (1-α) confidence interval, we look for an upper bound of the confidence interval so that α/2 of the residuals are above and a lower bound of the confidence interval so that α/2 of the residuals are below.

Let's consider the first case <img src="https://render.githubusercontent.com/render/math?math={ Y_{n%2B1}>\hat{q}_{n,\frac{\alpha}{2}}^{%2B}\{\hat{\mu}_{-i}(X_{n%2B1})(1%2BR_{i}^{LOO})\} }">. We have:
![image](https://user-images.githubusercontent.com/77614412/166113625-aee15a41-090c-4549-b3fd-7c16be3ac5bf.png)
and therefore <img src="https://render.githubusercontent.com/render/math?math={ n%2B1 \in S_{%2B}(A) }">, that is, point n+1 is a strange point with a high positive residual. Similarly, we can conclude the same for strange point with a high negative residual. Combining with step 2, we have:
![image](https://user-images.githubusercontent.com/77614412/166113633-1e358960-fcfa-4de2-810d-d8493ea2a2ae.png)
Since any point cannot be simultaneously in <img src="https://render.githubusercontent.com/render/math?math={ S_{%2B}(A) }"> and <img src="https://render.githubusercontent.com/render/math?math={ S_{-}(A) }"> otherwise <img src="https://render.githubusercontent.com/render/math?math={ \alpha \geq 1 }">, a point is either in none of the two sets or in only one of them.

![image](https://user-images.githubusercontent.com/77614412/166112844-1be58a6e-0d3a-4604-9fda-7fe36e278d83.png)

I am interested in any comment you may have. If you see a mistake, please point it out.
If there is no mistake, I don't see what prevent us to use other residual scores, for instance a Poisson one or Tweedie ones to adjust the relationship between the mean and the variance

**Comment by nilslacroix** [comment]
I do not really feel qualified to comment on this however I am still a bit unsure when to use this. I like the idea of scaling residuals since (as you said before) in many cases it can be expected to have an increased width when the target value is higher.

My question would rather be when to use this kind of score or when it is appropiate. 

Let me illustrate with an example. I have areal world data set with house prices (much like the kaggle challenges) and my target value SalePrice looks like this unscaled:

![image](https://user-images.githubusercontent.com/56065345/166141459-d07b544b-fd86-4e55-b66f-076acbd78635.png)

An like this when I apply `log(1+x)`:

![image](https://user-images.githubusercontent.com/56065345/166141428-19b3d5f4-93e3-4c9c-b487-ede11e71e43d.png)

In the unscaled case the original distribution looks much more like a gamma distribution, however when I do the log transformation it is much more like a normal distribution.

What would be the intuitive work flow here? Take the log transformed target, use gamma residual scoring, transform it back with `np.expm1()` ? Or should you stick with the original distribution which will probably lead to bad results with many algorithms? Do you think it makes even sense to use the gamme residual scoring on any normal distributed target?

To be clear I am no expert at all, I am not even sure if it is viable to transform something that is clearly not normal distributed with a log function and use something like mapie to compute prediction intervals. After all prediction/confidence intervals assume that there is normal distribution, which is true for the transformed target - but not when I transform it back to its original? I guess I am confused now :D

**Comment by kapytaine** [comment]
I am not an expert either.

If I were you, if I had chosen to work on the original data (without log), I would have preferred a regression model with a Gamma objective function. Then I would have use MAPIE to get the confidence intervals with a Gamma residual score. As you pointed it out, I am not entirely satisfied with using the Normal residual score on a Gamma regression.

If I had chosen to work on the log transformed data, which is a good idea I think, I would have preferred a regression model with the mean square objective function (i.e. I assume the new target to be normally distributed). Then I would have use MAPIE to get confidence intervals with the Normal residual score. To get the final confidence interval, I would finally take the exponential to get back the original unit.

Anyway, I would suggest you to look at different approaches and compare the results. I did it during my first investigation, and sometimes different approaches gave similar results.
