### ISSUE TITLE
Can't run any of the examples

### ISSUE THREAD

**Issue by neemashahbazi** [scikit-learn-contrib/MAPIE#153]
Using python 3.8 and latest version of sklearn 
This is the error I get:
`from sklearn.utils.validation import (
ImportError: cannot import name '_check_y' from 'sklearn.utils.validation' (/Users/nimashahbazi/PycharmProjects/distrust/venv/lib/python3.9/site-packages/sklearn/utils/validation.py)
`
Any ideas how to fix it?

**Comment by gmartinonQM** [comment]
Hi @neemashahbazi , what are your versions of MAPIE and scikit-learn ? You mention python 3.8 but your error message is python 3.9.

**Comment by neemashahbazi** [comment]
Problem solved by installing Python 3.10.
