### ISSUE TITLE
np.setdiff1D in class Subsample

### ISSUE THREAD

**Issue by gmartinonQM** [scikit-learn-contrib/MAPIE#165]
Hi all,

I have discovered this utility function of numpy : https://numpy.org/doc/stable/reference/generated/numpy.setdiff1d.html

that could be a nice fit for this line of code , and better optimized I think :

https://github.com/scikit-learn-contrib/MAPIE/blob/462207aae5bde9244aa03e005adacc2fe66e14a4/mapie/subsample.py#L89

The code would look like 
```
test_index = np.setdiff1d(indices, train_index)
```

instead of the current 

```
test_index = np.array(
                list(set(indices) - set(train_index)), dtype=np.int64
            )

**Comment by vtaquet** [comment]
Hey @gmartinonQM ! Thanks for your feedback, we will implement it in the coming release.
