### ISSUE TITLE
Varying width of prediction intervals with "base" method

### ISSUE THREAD

**Issue by juliuskittler** [scikit-learn-contrib/MAPIE#171]
I have a clarification question regarding the "base" method with the default 5-fold cross-validation.

When I use the MapieRegressor with `method = "base"` and leave the remaining arguments as default (i.e. `cv = None`, which corresponds to 5-fold cross validation), I expect that all my prediction intervals will have the same width for unseen test data points. 

For each test data point, the prediction interval will be centred at the prediction for this test data point. But the width of each prediction interval will be the same for all test data points because it's based on the holdout sets from the training data, not on the test data. I am referring to the paper "Predictive Inference with the Jackknife+":

<img width="631" alt="image" src="https://user-images.githubusercontent.com/39234739/171438228-a45a5604-abd7-4472-8bf9-73b3919bf7fd.png">

However, what I have noticed is that the width of the prediction intervals seems to **vary** for different test points when I use the MapieRegressor with method = "base" and leave the remaining arguments as default. Could you please explain where my thinking is mistaken? Does the width of the PI indeed vary for different test points and if so why?

**Comment by juliuskittler** [comment]
Answering my own question: The issue is that my regression target is log-scaled. MAPIE does not take that into account. 

MAPIE adds the *same* log-scaled error quantile to each log-scaled prediction. However, because the values will get unscaled later with an exponential function, the log-scaled error quantiles - although they are same for all predictions - have a different effect on the width of the prediction interval, depending on the value of the log-scaled prediction.

Therefore, when I unscale the log-scaled prediction intervals, I essentially get wider prediction intervals for predictions with larger values.

Maybe the documentation should mention this issue and warn that MAPIE should only be used if the regression target variable does not require scaling.

**Comment by vtaquet** [comment]
Hi @juliuskittler, thanks for raising this issue. This is indeed due to the fact that MAPIE does not take log-scaled effect into account when computing the prediction intervals. A PR aiming at implementing custom residual functions is in progress so you'll be able to implement log-scaled residuals very soon.
