### ISSUE TITLE
Test coverage not at 100% for `conformity_scores.py`

### ISSUE THREAD

**Issue by vtaquet** [scikit-learn-contrib/MAPIE#181]
**Describe the bug**
`conformity_scores.py` is not entirely test, leading to a test coverage of 90%. 

Add new tests for setting the coverage to 100%.

**Comment by LacombeLouis** [comment]
It would seem like the coverage is not at 100% for other files too, not just conformity_scores (see screenshot attached).
<img width="729" alt="Screenshot 2022-06-21 at 09 56 54" src="https://user-images.githubusercontent.com/63096108/174747481-46aa915b-45f7-4b79-832f-8fc344ddb262.png">
