### ISSUE TITLE
No module named 'mapie.quantile_regression'

### ISSUE THREAD

**Issue by masakljun** [scikit-learn-contrib/MAPIE#198]
**Describe the bug**
Hi! I wanted to use conformalized_quantile_regression for which I need the mapie.quantile_regression import. However, I tried a couple of things but cannot get it working. Is there any other way to use conformalized_quantile_regression with your library? Thanks in advance :)

**To Reproduce**
from mapie.quantile_regression import MapieQuantileRegressor
Error: No module named 'mapie.quantile_regression'

**Expected behavior**
I expected that I could use Conformal Quantile Regression but have not managed to import mapie.quantile_regression.

**Desktop (please complete the following information):**
 - OS:Windows
 - Browser: Chrome
 - MAPIE Version : 0.3.2

**Comment by masakljun** [comment]
Thank you!

**Comment by vtaquet** [comment]
Yes, we are working on a complete tutorial describing the difference between classic QR and conformalized QR. In the mean time, all examples using `MapieQuantileRegressor` can be found at the bottom on the API documentation webpage : https://mapie.readthedocs.io/en/latest/generated/mapie.quantile_regression.MapieQuantileRegressor.html#mapie.quantile_regression.MapieQuantileRegressor

**Comment by masakljun** [comment]
Thanks, I will check out the examples!
And also looking forward to the complete tutorial, because I am already encountering some further errors now as well (e.g., when trying to use XGBoost (which worked fine with classic QR) I am getting: _ValueError: The base model does not seem to be accepted by MapieQuantileRegressor. Give a base model among: ``quantile_estimator_params.keys()``Or, add your base model to ``quantile_estimator_params``."_).__
