### ISSUE TITLE
Asymmetric Jackknife+

### ISSUE THREAD

**Issue by christian-igel** [scikit-learn-contrib/MAPIE#208]
Thank you for your library! 
In „Predictive inference with the Jackknife+“, Barber et al. (201) suggest an asymmetric Jackknife+ in Appendix A. 
Could asymmetric versions of the algorithms considering the signed residuals be added?

**Comment by christian-igel** [comment]
Can I simply make a new `ConformityScore` by copying the `AbsoluteConformityScore`, changing `sym=False`, and passing it as an argument?

**Comment by vtaquet** [comment]
Hi @christian-igel ! Yes, this is exactly what I was about to suggest. It would be really easy to implement. Please let us know if you have some problems or if you have some cool results to share.
