### ISSUE TITLE
Jackknife+-after-Bootstrap for ensemble models

### ISSUE THREAD

**Issue by kjelljorner** [scikit-learn-contrib/MAPIE#218]
In the original [article](https://arxiv.org/pdf/2002.09025.pdf) on the Jackknife+-after-Bootstrap, one of the selling points is that ensemble models such as Random Forest already consist of a set of bootstrapped models that can be recycled to give the prediction interval with the Jackknife+. Therefore, the prediction intervals are "free" in the same sense as the out-of-bag score is free in relation to cross-validation and bootstrapping for the prediction error.

Is there some way to leverage this approach in MAPIE? Currently, it seems like `MapieRegressor` with `SubSample` would always retrain the given estimator, and in the case of Random Forest, give an ensemble of ensembles.

**Comment by kjelljorner** [comment]
Hello @vincentblot28. First of all, thanks for putting this amazing library together. I understand the general idea, but as you anyway expect a scikit-learn estimator, you could possibly do `isinstance` checks for `RandomForestRegressor` or `hasattr` checks for `estimators_`. I think this would not reduce the agnosticticity of your library.

**Comment by vincentblot28** [comment]
Hello @kjelljorner,

Yes I think that a check in `isinstance` should do it ! For now we try to develop methods that can be applied to any models, but we keep this idea in mind for future developments ! 
Thanks !
