### ISSUE TITLE
Example of taking lagged values of a time-series and producing CDF

### ISSUE THREAD

**Issue by microprediction** [scikit-learn-contrib/MAPIE#219]
It would be nice to see a simple example of taking a univariate time-series and producing k CDFs for the next k points in the series. 

## Motivation 

The motivation for this is rather simple. It is the only little thing required to embed conformal prediction into a microprediction crawler, where it can scurry around and make all manner of distributional predictions of a menagerie of live time-series. Anyone could make modifications as they see fit. 

I'll drop this issue in the slack. A ConformalCrawler is really way overdue. 

PS: Sorry if this is motivation/verbiage is mildly obscure. I once made the mistake of including explanatory links and a GitHub bot kicked me off. It should be easy to google.

**Comment by microprediction** [comment]
Hi Thomas,
    Yes, k=1 is a good place to start I agree. I created a colab [notebook](https://github.com/microprediction/timeseries-notebooks/blob/main/mapie_with_timemachines.ipynb) that performers sequential point prediction for k=1 and collates the history of observations and predictions. 
Peter

**Comment by tmorzade** [comment]
Hi Peter,
Thank you!
But it seems that the online version is not endeed yet. I mean you don't use MAPIE
Thomas

**Comment by thibaultcordier** [comment]
I propose to close this issue due to the lack of activity and because this item is not planned.
