### ISSUE TITLE
Long-term MapieRegressor Storage

### ISSUE THREAD

**Issue by tjstruck** [scikit-learn-contrib/MAPIE#220]
Greetings, our research lab is planning on storing many trained MapieRegressor objects. Because Pickle has potential version issues when loading objects, we were wondering if there is a simple long-term storage solution for MapieRegressor objects that can preserve the ability to calculate predictions and confidence intervals. 

Alternatively, scikit-learn's MLPRegressor objects can be converted to an interoperable format using Open Neural Network Exchange (ONNX, https://onnx.ai/index.html), so it might be worthwhile to work with the ONNX devs to add Mapie compatibility with ONNX.

**Comment by vincentblot28** [comment]
Hello @tjstruck !
Thank you for your interest in our package ! There are no long-term storage solution for MapieRegressor yet. 

One possible way of doing it right now is to save each of the estimators and then reload them in the `self.estimators_` class attribute before doing the predict. You should as well load the conformity scores computed during the `fit` and change some other class attributes (e.g. the fit attributes). I think it is the only way of including ONNX in Mapie today. 

Our roadmap doesn't currently include à ONNX compatibility but if ever you want to add it to MAPIE we would be very happy if you make a pull request !
