### ISSUE TITLE
When labels don't go from 0 to L

### ISSUE THREAD

**Issue by LacombeLouis** [scikit-learn-contrib/MAPIE#235]
**Describe the bug**
If the labels are not from 0 to L, then there is an error. Simply making the labels go from 1 to L+1 raises an error.

**To Reproduce**
To reproduce, run the following python code:
from sklearn.datasets import make_classification
from mapie.classification import MapieClassifier

random_state = 20

X, y = make_classification(
    n_samples=20000,
    n_classes=4,
    n_informative=6,
    random_state=random_state
)
y += 1

mapie = MapieClassifier()
mapie.fit(X, y)

error message: `IndexError: index 4 is out of bounds for axis 1 with size 4`

**Expected behavior**
I would either expect an error message to warn that the labels should start at 0, or simply fix to allocate the label to the the correct column.

**Desktop (please complete the following information):**
 - MAPIE Version 0.5.0
 - Python 3.10.6

**Additional context**

**Comment by vincentblot28** [comment]
Fixed by PR #279
