### ISSUE TITLE
Sparse matrix when using CV methods

### ISSUE THREAD

**Issue by gmartinonQM** [scikit-learn-contrib/MAPIE#239]
I had a problem recently using MAPIE with the CV+ method. I had to train MAPIE on 200 000 samples and predict on 50 000 samples. It appears that this create an intermediate matrix of size `(n_samples_train, n_samples_test)`, which can be very large, and crash the RAM. I circumvented the problem by producing predictions by smaller batches, of say 1000 samples.

Would it be possible to store this intermediate `(n_samples_train, n_samples_test)` matrix as a sparse array, in order to save memory usage ?

**Comment by vtaquet** [comment]
Hi @gmartinonQM , I think your issue is also related to issue #160 but has not been solved yet...

**Comment by vincentblot28** [comment]
I'm closing this issue as it is a duplicate of #160
