### ISSUE TITLE
question - Does MAPIE support multiple time series in tabular format?

### ISSUE THREAD

**Issue by Arsa-Nik** [scikit-learn-contrib/MAPIE#243]
I wonder whether MapieTimeSeriesRegressor supports building prediction interval when input data is tabular form and contains multiple time series. Specifically how does it know to pull the right residuals in BlockBootstrap to build distribution when the scales of times series in input data are significantly different?

**Comment by tmorzade** [comment]
Hello,
Thank you very much for your issue,
Currently MapieTimeSeriesRegressor does not suit for multiple time series. It is based on residuals, and the residuals stored in mapie model only correspond to a single time series

We will let you know if future enhancement offers to apply mapie to multiple time series
With regards,
Thomas

**Comment by thibaultcordier** [comment]
The original question has been answered. For multi-output regression, see related issue: #97. In this way, the issue can be closed as completed.
