### ISSUE TITLE
Clarification of the "symmetry" argument in CQR and more general documentation about CQR

### ISSUE THREAD

**Issue by gmartinonQM** [scikit-learn-contrib/MAPIE#249]
Hi all, and thanks again for all your developments of MAPIE ! 

I recently struggled with CQR, wondering what was the impact of the `symmetry` argument in `MapieQuantileRegressor.predict` function. The docstring is quite elusive : 

_"Deciding factor to whether to find the quantile value for each residuals separatly or to use the maximum of the two combined."_ 

(BTW there is a typo on "separatly" -> "separately").

And I cannot find more information, be it in the theoretical description, the tutorial on CQR or the 1D-heteroscedastic example.

Would it be possible to better describe the impact of the argument and to illustrate it in the tutorial for example ? 

Moreover, I am not sure that I understand the notations in the theoretical description. For example, there are three different notations `E_i`, `E_{low}` and `E_{high}` but none is defined. As for the vocabulary, I find the word "residual" confusing in the context of CQR, because it suggests that we compute the difference between the target and the main model prediction (the median estimator) whereas we compare with the other two quantiles. 

![Capture d’écran 2023-01-05 à 22 15 30](https://user-images.githubusercontent.com/57913701/210881392-c308ebfb-70bf-4dc0-9c44-9cdc6417905c.png)

Would it be possible to clarify these points ? 

Thanks in advance !

**Comment by nmdwolf** [comment]
The standard implementation uses the maximum of the lower and upper quantile residuals. However, one could generalize this method to correct the lower and upper quantiles independently (with some correction as to maintain the required significance level). I assume this is what they mean.
