### ISSUE TITLE
Uncertainty Feature Attribution ?

### ISSUE THREAD

**Issue by lcrmorin** [scikit-learn-contrib/MAPIE#258]
I'd like to 'explain' uncertainty with some form of feature attribution. This would be helpfull for both knowing the data and possibly target the data quality improvement if necessary. 

Ideally i'd like a pred_contrib parameter similar to lgbm predict function, where if set to True the prediction would be of size (n_sample, 3+n_features, alpha). The prediction would contain some uncertainty feature attribution; 

However, its not entirely clear of how the theoretical framework would allow this.

**Comment by vincentblot28** [comment]
Hi @lcrmorin, thank you for your issue. For now this implementation is not planned. We are not aware of any paper related to this issue, if you have one we would be glad to read it. I will close the issue for now, feel free to re-open it if you encounter a paper that tackles this issue !

**Comment by lcrmorin** [comment]
Hmmm ok, maybe my question was about the existence of said literrature; I will keep an eye open for such a paper.
