### ISSUE TITLE
Still getting large prediction sets when all classes but one have probability 0

### ISSUE THREAD

**Issue by christophM** [scikit-learn-contrib/MAPIE#266]
Basically the same as #254 , but with a different dataset. 

I updated to MAPIE 0.6.0 and the large-set problem  (#254) vanished for the Iris dataset, but it still persists for a different data set (bean dataset, see reproducible example below).

**Describe the bug**

Using MapieClassifier with method="cumulated_score" produces large prediction sets (that include all 7 classes) for instances where all probabilities are (practically) 0 except for 1 class where it's 1 .
**To Reproduce**

```Python
import os
import wget
import zipfile
from os.path import exists
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB

from mapie.classification import MapieClassifier

# Download if not available
bean_data_file = "./DryBeanDataset/Dry_Bean_Dataset.xlsx"
base = "https://archive.ics.uci.edu/ml/machine-learning-databases/00602/"
if not exists(bean_data_file):
  filename = "DryBeanDataset.zip"
  url = base + filename
  wget.download(url)
  with zipfile.ZipFile(filename, 'r') as zip_ref:
    zip_ref.extractall('./')
  os.remove(filename)


# Read in the data from Excel file
beans = pd.read_excel(bean_data_file)
# Labels are characters but should be integers for sklearn
le = LabelEncoder()
beans["Class"] = le.fit_transform(beans["Class"])
# Split data into classification target and features
y = beans["Class"]
X = beans.drop("Class", axis = 1)

# Split of training data
X_train, X_rest, y_train, y_rest = train_test_split(
  X, y, train_size=10000, random_state=2
)

# Split remaining into calibration and "new" data
X_calib, X_new, y_calib, y_new = train_test_split(
  X_rest, y_rest, train_size=1000, random_state=42
)

# Fit the model
model = GaussianNB().fit(X_train, y_train)
mapie_score = MapieClassifier(model, cv="prefit",
                method="cumulated_score",
                random_state=1)
mapie_score.fit(X_calib, y_calib)

y_pred, y_set = mapie_score.predict(X_new, alpha=0.05, include_last_label=False)
y_set = np.squeeze(y_set)

all_classes = np.sum(y_set, axis=1) == 7
model.predict_proba(X_new)[all_classes][0]
```

```
array([1.62871888e-044, 1.00000000e+000, 2.53250146e-051, 0.00000000e+000,
       1.10232357e-132, 0.00000000e+000, 0.00000000e+000])
```

```python
mapie_score.quantiles_
```

```
array([0.99951011])
```

**Expected behavior**
I would expect that these cases would result in prediction sets with just one class.

**Desktop (please complete the following information):**

- OS: MacOS
- Python (3.10.7)
- MAPIE Version 0.6.0

Thanks!

**Comment by vincentblot28** [comment]
Hello @christophM, 

Indeed, my previous fix was too restrictive and only took into account the case where you had exact 0 scores in your predictions. I changed this 0 to EPSILON and it fixes your issue. Their will be a release this week to take it into account

Vincent

**Comment by christophM** [comment]
Again, thanks a lot for being so responsive and helpful!

By the way, I'm writing a book about conformal prediction with code examples using MAPIE. The way you professionally handle bugs makes me even more confident to recommend MAPIE.

**Comment by vincentblot28** [comment]
It's a great news, can't wait to read it ! 
I've just done a new release (0.6.1) in order to include the fixe !
