### ISSUE TITLE
Compatibility with survival analysis packages as scikit-survival?

### ISSUE THREAD

**Issue by joselznom** [scikit-learn-contrib/MAPIE#271]
I am a frequent user of the MAPE package and I wanted to inquire about the possibility of adding compatibility with survival analysis packages for censored data, such as scikit-survival.

If possible, could you please consider adding compatibility with survival analysis packages for censored data in a future update of MAPE? I believe this would be a valuable addition to an already great package, and I'm sure many other users would find it helpful as well.

Thank you for your time and consideration

**Comment by vincentblot28** [comment]
Hi @joselznom , thank you for your issue. For now this implementation is not planned. We are not aware of any paper related to this issue, if you have one we would be glad to read it. I will close the issue for now, feel free to re-open it if you encounter a paper that tackles this issue !

**Comment by joselznom** [comment]
Hi @vincentblot28,
Here are a couple of papers that are related to the topic:
https://academic.oup.com/jrsssb/article/85/1/24/7008653?login=false#396975853
https://ieeexplore.ieee.org/document/8260735
