### ISSUE TITLE
Inconsistency in setup.py

### ISSUE THREAD

**Issue by JulienRoussel77** [scikit-learn-contrib/MAPIE#272]
The file setup.py contains 'tests' and 'doc' extras which are not designed for the final user. I would rather have these libraires in separate requirements.***.txt, similarly to what is done for requirements.dev.txt.

**Comment by thibaultcordier** [comment]
Hello @JulienRoussel77, @gmartinonQM,

I have proposed a pull request to solve this problem. But before merging, I would like to be sure about your request. Indeed, I checked in the [setup.py of scikit learn] (https://github.com/scikit-learn/scikit-learn/blob/main/setup.py) to compare. The file also defines these additional requirements "extras_require".

So here is my question: what was the original motivation for this addition in the MAPIE setup.py? Do you confirm that this addition is not relevant today?

I can propose you to keep the setup.py file without modification (like scikit-learn) but I can add requirements.test.txt and requirements.doc.txt.
