### ISSUE TITLE
A question about sample_weights

### ISSUE THREAD

**Issue by mrticker** [scikit-learn-contrib/MAPIE#276]
I have a question. If you use sample_weights in `MapieRegressor.fit()`, does it correspond to the method described in Tibshirani's Conformal Prediction Under Covariate Shift, or are they used for something else?

**Comment by vincentblot28** [comment]
Hello @mrticker, for now, the sample_weights argument is only used as argument to fit the estimator but this PR (https://github.com/scikit-learn-contrib/MAPIE/pull/151) is implementing the Tibshirani method, so it should be ready in the folllowing weeks
