### ISSUE TITLE
Unit test for different subsamples

### ISSUE THREAD

**Issue by gmartinonQM** [scikit-learn-contrib/MAPIE#290]
I have noticed that samples generated by the `Subsample` class all share the same random state.
https://github.com/scikit-learn-contrib/MAPIE/blob/2d7fecb1491ebc8d60d6a970a14ed6ba6441da41/mapie/subsample.py#L86

This suggests that all bootstraps are drawned with the same seed. However, quick experiments show that this is not the case.

Would it be possible to add a unit test to ensure that all samples drawn are different ? The same is true for blockbootstrap by the way.

Here is a suggestion : 

```python
import numpy as np
import pytest

from mapie.subsample import Subsample

def test_split_SubSample_different_amples() -> None:
    """Test that outputs of subsamplings are all different."""
    X = np.array([0, 1, 2, 3])
    cv = Subsample(n_resamplings=2, random_state=1)
    trains = [x[0] for x in cv.split(X)]
    tests = [x[1] for x in cv.split(X)]
    with np.testing.assert_raises(AssertionError):
         np.testing.assert_equal(trains[0], trains[1])
    with np.testing.assert_raises(AssertionError):
         np.testing.assert_equal(tests[0], tests[1])

```

**Comment by LacombeLouis** [comment]
Closed with #468.
