### ISSUE TITLE
Cannot import MapieQuantileRegressor

### ISSUE THREAD

**Issue by joshdunnlime** [scikit-learn-contrib/MAPIE#313]
**Cannot Import MapieQuantileRegressor**

**To Reproduce**
```bash
pip install mapie
```

then

```python
from mapie.regression import MapieQuantileRegressor, MapieRegressor
```

> ImportError: cannot import name 'MapieQuantileRegressor' from 'mapie.regression' (mambaforge/envs/ltf-analysis/lib/python3.9/site-packages/mapie/regression.py)

```python
from mapie.regression import MapieRegressor
```
^ this works however.

**Expected behavior**
To import the class.

**Desktop (please complete the following information):**
 - OS: Mac M1
 - MAPIE Version: 0.6.4

**Comment by thibaultcordier** [comment]
Try the following import:
```python
from mapie.quantile_regression import MapieQuantileRegressor
```
Can you confirm that it works?
