### ISSUE TITLE
Add checks for metrics

### ISSUE THREAD

**Issue by LacombeLouis** [scikit-learn-contrib/MAPIE#330]
Would be good to add additional checks for the metrics.
For example:

- check that `y_true` and `y_pred` are the same length
- check that there are no Nans

Simple check to assure that the user has good feedback upon error in metric.

**Comment by JumpingDino** [comment]
Is it okay if I try to do this one?

I expect to create two functions
- check_array_length
- check_array_nan
which will try to make these checks for the metrics inside metrics.py

**Comment by thibaultcordier** [comment]
Hello @JumpingDino, that's a good suggestion for solving this issue, thank you.
You can fork the repositoty (see [CONTRIBUTING.rst](https://github.com/scikit-learn-contrib/MAPIE/blob/master/CONTRIBUTING.rst)) and propose a pull request with these functions in the `mapie/utils.py` file and their corresponding tests. Don't hesitate to ask for help during implementation.
