### ISSUE TITLE
RAPS calibration

### ISSUE THREAD

**Issue by vahuja4** [scikit-learn-contrib/MAPIE#342]
Can someone please explain why MAPIE doesn't allow cross-validation while calibrating RAPS parameters.

**Comment by thibaultcordier** [comment]
Hello @vahuja4,

Thank you for your patience. To my knowledge, this method was proposed by Angelopoulos et al. [1]. And our first motivation is to re-implement the algorithms as presented in the scientific papers.

To quote them, the authors "_use a convenient data-splitting version known as split conformal prediction that enables conformal prediction methods to be deployed for essentially any predictor_".

To be verified, but it may be possible that the *cross conformal prediction* version of the algorithm is also valid, but the article doesn't mention it. As I write this reply, I don't know the answer, but I'll look into it.

[1] Anastasios Nikolas Angelopoulos, Stephen Bates, Michael Jordan and Jitendra Malik. “Uncertainty Sets for Image Classifiers using Conformal Prediction.” International Conference on Learning Representations 2021. (https://arxiv.org/abs/2009.14193)
[_] MAPIE Documentation : https://mapie.readthedocs.io/en/stable/theoretical_description_classification.html
