### ISSUE TITLE
Trivial typo in `quantile_regression.py` and `time_series_regression.py`

### ISSUE THREAD

**Issue by Carl-McBride-Ellis** [scikit-learn-contrib/MAPIE#364]
**Describe the bug**
* There is a trivial typo in the file [`quantile_regression.py`](https://github.com/scikit-learn-contrib/MAPIE/blob/7820eed3388de65bcaea8a41c6640289acfce32d/mapie/quantile_regression.py#L9C7-L9C11)
* There is a trivial typo in the file [`time_series_regression.py`](https://github.com/scikit-learn-contrib/MAPIE/blob/7820eed3388de65bcaea8a41c6640289acfce32d/mapie/time_series_regression.py#L9C7-L9C11)

**Expected behavior**
In both files it should read `from` rather than `form` 
(only noticed this when cutting-and-pasting into my code which failed).

All the best,
carl

**Comment by thibaultcordier** [comment]
Thank you @Carl-McBride-Ellis, I'm going to start a PR to correct this trivial typo.
