### ISSUE TITLE
Reference for Residual Normalized Score 

### ISSUE THREAD

**Issue by vincentblot28** [scikit-learn-contrib/MAPIE#366]
Hello, I think the reference for the Residual Normalized score is not the good one it should be 

Lei et al., “Distribution-Free Predictive Inference For Regression.”

Instead of the gentle Introduction

**Comment by mehdi-elion** [comment]
Hello @vincentblot28 ! If that's possible, I'd like to work on this issue.
Let me know if you're ok with this :)

cc: @LacombeLouis

**Comment by mehdi-elion** [comment]
@vincentblot28 I fixed the reference for the residual normalised score.
I tried to follow the contribution guideline and the PR checklist. 
Let me know if something is wrong or needs fixing 👍 

cc: @LacombeLouis
