### ISSUE TITLE
Incoherent sign on C_k in the Kolmogorov-Smirnov statistical test documentation

### ISSUE THREAD

**Issue by JulienRoussel77** [scikit-learn-contrib/MAPIE#369]
The formula for C_k presented [here](https://mapie.readthedocs.io/en/latest/theoretical_description_metrics.html#:~:text=Kolmogorov%2DSmirnov%20Statistic%20for,%C2%B6) has a sign convention that is the opposite of the implementation in the function mapie.metrics.kolmogorov_smirnov_statistic :[ link](https://mapie.readthedocs.io/en/latest/theoretical_description_metrics.html#:~:text=Kolmogorov%2DSmirnov%20Statistic%20for,%C2%B6)

**Comment by BaptisteCalot** [comment]
I seems to be good and the code matches the documentation

1- Here is the [code](https://mapie.readthedocs.io/en/latest/_modules/mapie/metrics.html#cumulative_differences)

2- Here is the [doc](https://mapie.readthedocs.io/en/latest/theoretical_description_metrics.html#:~:text=multi%2Dclass%20problems.-,Cumulative%20Differences,%C2%B6,-Cumulative%20Differences%20calculates)

@LacombeLouis can you confirm my observation please ?

**Comment by BaptisteCalot** [comment]
I have changed the title of the issue as well as its description: the sign error into C_k (cumulative difference) comes from the Kolmogorov-Smirnov statistical test, not from the cumulative difference metric
