### ISSUE TITLE
UPD: Refactorisation of MapieClassifier

### ISSUE THREAD

**Issue by candicemyt** [scikit-learn-contrib/MAPIE#376]
**Is your feature request related to a problem? Please describe.**
The ``MapieClassifier`` class needs to be aligned with the ``MapieRegressor``.

**Describe the solution you'd like**
The computation of the conformity scores (currently called ``method``) should be done in a separate class as well as the handling of the base predictor.

**Comment by Valentin-Laurent** [comment]
Hello @candicemyt.
This issue is quite old, is this still relevant?

**Comment by candicemyt** [comment]
Hello @Valentin-Laurent, this has been resolved by #476
