### ISSUE TITLE
Inconsistent result in unit test for "aps_randomized_cv_crossval" in classification

### ISSUE THREAD

**Issue by thibaultcordier** [scikit-learn-contrib/MAPIE#377]
**Describe the bug**
When the unit tests are run, one test gives inconsistent results (for the "aps_randomized_cv_crossval" method in the classification).

**To Reproduce**
1. Run the `test_toy_dataset_predictions` test several times in `mapie/tests/test_classification.py`.

**Expected behavior**
Consistent results when tests are run several times.

**Comment by Sialcant** [comment]
Hello everyone,

@thibaultcordier I confirm the comment made by @BaptisteCalot above.

Running `test_toy_dataset_predictions` with `strategy = "aps_randomized_cv_crossval"` 10k times is not giving me any error. 

See the test function I created for that here :https://github.com/Sialcant/MAPIE-issue-377/blob/c633e2b71acef5d9d0b1f77f085a19a5e8e32b6e/mapie/tests/test_classification.py#L1461

Should I do something differently?

Best,

**Comment by thibaultcordier** [comment]
Hello @BaptisteCalot @BenoitGaston 

Your feedback seems to be good and experience shows that the problem has not reappeared.
I am closing the issue accordingly.

Best,
