### ISSUE TITLE
Small typo in jackknife description (closed->close)

### ISSUE THREAD

**Issue by pidefrem** [scikit-learn-contrib/MAPIE#392]
**Is your documentation request related to a problem? Please describe.**
Just fixing a small typo in the documentation
https://mapie.readthedocs.io/en/latest/theoretical_description_regression.html#the-jackknife-method

**Describe the solution you'd like**
Replace "closed" by "close" in the following paragraph:
* original: "This method avoids the overfitting problem but can lose its predictive cover when \hat{\mu} becomes unstable, for example when the sample size is **closed** to the number of features (as seen in the “Reproducing the simulations from Foygel-Barber et al. (2020)” example)."
* fixed: "This method avoids the overfitting problem but can lose its predictive cover when \hat{\mu} becomes unstable, for example when the sample size is **close** to the number of features (as seen in the “Reproducing the simulations from Foygel-Barber et al. (2020)” example)."

**Comment by isaiahthedev** [comment]
Hi, can I be assigned to this? I corrected the mistake and noticed some other spelling errors on that particular file which I also corrected.
