### ISSUE TITLE
Citation /bib file

### ISSUE THREAD

**Issue by Ciaran1981** [scikit-learn-contrib/MAPIE#394]
Is there a preferred citation for the use of this library? I plan to cite it in a paper...

**Comment by thibaultcordier** [comment]
@article{taquet2022mapie,
  title={MAPIE: an open-source library for distribution-free uncertainty quantification},
  author={Taquet, Vianney and Blot, Vincent and Morzadec, Thomas and Lacombe, Louis and Brunel, Nicolas},
  journal={arXiv preprint arXiv:2207.12274},
  year={2022}
}

**Comment by thibaultcordier** [comment]
To date, we do not offer direct citations for the MAPIE project on GitHub, but we have published two scientific papers presenting the MAPIE project, the latest at the COPA 2023 conference (see [this link](https://cml.rhul.ac.uk/copa2023/#nav-program) and [the paper](https://proceedings.mlr.press/v204/cordier23a/cordier23a.pdf)):
```
@inproceedings{cordier2023flexible,
  title={Flexible and Systematic Uncertainty Estimation with Conformal Prediction via the MAPIE library},
  author={Cordier, Thibault and Blot, Vincent and Lacombe, Louis and Morzadec, Thomas and Capitaine, Arnaud and Brunel, Nicolas},
  booktitle={Conformal and Probabilistic Prediction with Applications},
  pages={549--581},
  year={2023},
  organization={PMLR}
}
```

```
@article{taquet2022mapie,
  title={MAPIE: an open-source library for distribution-free uncertainty quantification},
  author={Taquet, Vianney and Blot, Vincent and Morzadec, Thomas and Lacombe, Louis and Brunel, Nicolas},
  journal={arXiv preprint arXiv:2207.12274},
  year={2022}
}
```

**Comment by Ciaran1981** [comment]
Excellent thanks again - handy to know about the github tool
