### ISSUE TITLE
About the name MapieRegressor and others

### ISSUE THREAD

**Issue by gmartinonQM** [scikit-learn-contrib/MAPIE#397]
I was just thinking that original naming of MAPIE classes (for which I am part guilty) sounds a bit weird : MapieRegressor, MapieClassifier... In contrast, there is no SklearnRandomForest in scikit-learn.

I would advocate for clearer names, like ConformalRegressor, ConformalMultiClassClassifier. What do you think about it ?

**Comment by valeman** [comment]
The names would benefit from more clear link between the name and what the actual model is. E.g. CQR, Jackknife++ etc.

**Comment by Valentin-Laurent** [comment]
This issue will be addressed in v1.
