### ISSUE TITLE
Gradient Boosting Regressor Model

### ISSUE THREAD

**Issue by Karoloso** [scikit-learn-contrib/MAPIE#411]
Attempts to obtain confidence intervals for the GradientBoostingRegressor model. 
Below is the program code:

from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression
from sklearn.ensemble import GradientBoostingRegressor
from matplotlib import pyplot as plt
from mapie.regression import MapieQuantileRegressor

Model = GradientBoostingRegressor(
    n_estimators = 500,
    max_depth = 4,
    min_samples_split = 5,
    learning_rate = 0.01,
    loss = "squared_error",
)

X, y = make_regression(n_samples=5000, n_features=1, noise=20, random_state=59)
X_train, X_tmp,  y_train, y_tmp  = train_test_split(X, y, test_size=2000, random_state=42)
X_calib, X_test, y_calib, y_test = train_test_split(X_tmp, y_tmp, test_size=1000, random_state=42)

alpha = 0.1
mapie = MapieQuantileRegressor(estimator=Model, cv="split", alpha=alpha)
mapie.fit(X_train, y_train, X_calib=X_calib, y_calib=y_calib)
y_pred, y_pis = mapie.predict(X_test)

When I try to compile the code I get this error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-1-acc076579023>](https://localhost:8080/#) in <cell line: 24>()
     22 alpha = 0.1
     23 mapie = MapieQuantileRegressor(estimator=Model, cv="split", alpha=alpha)
---> 24 mapie.fit(X_train, y_train, X_calib=X_calib, y_calib=y_calib)
     25 y_pred, y_pis = mapie.predict(X_test)

1 frames
[/usr/local/lib/python3.10/dist-packages/mapie/regression/quantile_regression.py](https://localhost:8080/#) in _check_estimator(self, estimator)
    285                     if loss_name in param_estimator:
    286                         if param_estimator[loss_name] != "quantile":
--> 287                             raise ValueError(
    288                                 "You need to set the loss/objective argument"
    289                                 + " of your base model to ``quantile``."

**ValueError: You need to set the loss/objective argument of your base model to ``quantile``.**

 - MAPIE Version [ 0.8.2]

**Comment by LacombeLouis** [comment]
Hey @Karoloso,
Thank you for your issue. As suggested in the error raised, when using CQR which is a quantile based method, you need to set your regressor to use a quantile loss. In this context, it means that you need to set 

`
Model = GradientBoostingRegressor(n_estimators = 500, max_depth = 4, min_samples_split = 5, learning_rate = 0.01, loss = "quantile")
`

Note that if you wish to fit other models that are not preestablished in MAPIE, I refer you back to these issues: #409 #199.
I hope this solves your problem!

**Comment by Karoloso** [comment]
> Hey @Karoloso, Thank you for your issue. As suggested in the error raised, when using CQR which is a quantile based method, you need to set your regressor to use a quantile loss. In this context, it means that you need to set
> 
> `Model = GradientBoostingRegressor(n_estimators = 500, max_depth = 4, min_samples_split = 5, learning_rate = 0.01, loss = "quantile")`
> 
> Note that if you wish to fit other models that are not preestablished in MAPIE, I refer you back to these issues: #409 #199. I hope this solves your problem!

Thank you for your answer. The program has compiled.
I would also like to ask what could be the reason for such an error that occurs after running my program and how to avoid it:

/usr/local/lib/python3.10/dist-packages/mapie/utils.py:598: UserWarning: WARNING: The predictions have issues.
**The upper predictions are lower thanthe lower predictions at some points.**
  warnings.warn(

**Comment by Karoloso** [comment]
> Hey @Karoloso, Thank you for your issue. As suggested in the error raised, when using CQR which is a quantile based method, you need to set your regressor to use a quantile loss. In this context, it means that you need to set
> 
> `Model = GradientBoostingRegressor(n_estimators = 500, max_depth = 4, min_samples_split = 5, learning_rate = 0.01, loss = "quantile")`
> 
> Note that if you wish to fit other models that are not preestablished in MAPIE, I refer you back to these issues: #409 #199. I hope this solves your problem!

Thank you for your answer. The error stopped appearing. I would also like to print a table with predictions using this code: 

from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression
from sklearn.ensemble import GradientBoostingRegressor
from matplotlib import pyplot as plt
from mapie.regression import MapieQuantileRegressor

Model = GradientBoostingRegressor(
n_estimators = 500,
 max_depth = 4,
 min_samples_split = 5,
 learning_rate = 0.01,
 loss = "quantile")

X, y = make_regression(n_samples=5000, n_features=1, noise=20, random_state=59)
X_train, X_tmp,  y_train, y_tmp  = train_test_split(X, y, test_size=2000, random_state=42)
X_calib, X_test, y_calib, y_test = train_test_split(X_tmp, y_tmp, test_size=1000, random_state=42)

alpha = 0.1
mapie = MapieQuantileRegressor(estimator=Model, cv="split", alpha=alpha)
mapie.fit(X_train, y_train, X_calib=X_calib, y_calib=y_calib)
y_pred, y_pis = mapie.predict(X_test)

predictions = y_test.to_frame()
predictions.columns = ['y_true']
predictions["point prediction"] = y_pred
predictions["lower"] = y_pis.reshape(-1,2)[:,0]
predictions["upper"] = y_pis.reshape(-1,2)[:,1]
# take a quick look
predictions

Unfortunately, when trying to run the program, the following error appears:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-7-f02b5b6ad7c1>](https://localhost:8080/#) in <cell line: 26>()
     24 y_pred, y_pis = mapie.predict(X_test)
     25 
---> 26 predictions = y_test.to_frame()
     27 predictions.columns = ['y_true']
     28 predictions["point prediction"] = y_pred

**AttributeError: 'numpy.ndarray' object has no attribute 'to_frame'**

**Comment by Karoloso** [comment]
Thanks for help.
