### ISSUE TITLE
Does MAPIE support multi-step regression? I am using a Tensorflow Model with KerasRegressor

### ISSUE THREAD

**Issue by dani-vu** [scikit-learn-contrib/MAPIE#431]
I want to use MAPIE to get prediction intervals. This works for a single step output approach. However, when I want to look e.g. 10 timestamps into the future, I get the "ValueError: y should be a 1d array, got an array of shape (8190, 10) instead."

I am using LSTM for this example. When having a single step output, my model looks like this:

model = Sequential([layers.Input(shape=(X_train.shape[1], X_train.shape[2])),
                                  layers.LSTM(64, return_sequences=True),
                                  layers.Flatten(),
                                  layers.Dense(32, activation='relu'),
                                  layers.Dense(32, activation='relu'),
                                  layers.Dense(1)])

For the multi step approach, I changed my last Dense layer parameter to the number of timestamps that I want to look into the future, in this case 10:

model = Sequential([layers.Input(shape=(X_train.shape[1], X_train.shape[2])),
                                  layers.LSTM(64, return_sequences=True),
                                  layers.Flatten(),
                                  layers.Dense(32, activation='relu'),
                                  layers.Dense(32, activation='relu'),
                                  layers.Dense(10)])

But as mentioned, the "ValueError: y should be a 1d array, got an array of shape (8190, 10) instead." occurs.

The shape of my X is (8190, 32, 23) and the shape of y is(8190, 10)).

**Comment by LacombeLouis** [comment]
Hey @dani-vu,

That's something we have not yet implemented (see multi-output regression: #97). We only make for one time step ahead. Just to get more information about your issue, is this something that you would want to be implemented in `MapieTimeSeriesRegressor`?

For the moment, the alternative would be to iteratively do one prediction at a time.

Thank you,
Louis

**Comment by dani-vu** [comment]
Hey @LacombeLouis ,

thank you for the quick response. Yes, this is what I would want to be implemented in `MapieTimeSeriesRegressor`.

All the best,
Daniel

**Comment by Yulinwan** [comment]
> 嘿，
> 
> 这是我们尚未实现的东西（参见多输出回归：[#97](https://github.com/scikit-learn-contrib/MAPIE/issues/97)）。我们只领先一步。只是为了获得有关您的问题的更多信息，这是您希望实施的东西吗？`MapieTimeSeriesRegressor`
> 
> 目前，另一种选择是一次迭代地执行一个预测。
> 
> 谢谢你，路易斯

Hello! I encountered a problem while using ENPPI and I would like to consult with you if you can provide some advice. The implementation in the enbpi example is single step prediction. Can enbpi perform long-term prediction (common step sizes are 96192336720). Is there a suitable method to better apply ENPPI to long-term forecasting. Or, is enbpi suitable for long-term forecasting, and is there any conflict between the working principle of enbpi and long-term forecasting?

**Comment by Yulinwan** [comment]
> 嘿，
> 
> 这是我们尚未实现的东西（参见多输出回归：[#97](https://github.com/scikit-learn-contrib/MAPIE/issues/97)）。我们只领先一步。只是为了获得有关您的问题的更多信息，这是您希望实施的东西吗？`MapieTimeSeriesRegressor`
> 
> 目前，另一种选择是一次迭代地执行一个预测。
> 
> 谢谢你，路易斯

Hello! I encountered a problem while using ENPPI and I would like to consult with you if you can provide some advice. The implementation in the enbpi example is single step prediction. Can enbpi perform long-term prediction (common step sizes are 96，192，336，720). Is there a suitable method to better apply ENPPI to long-term forecasting. Or, is enbpi suitable for long-term forecasting, and is there any conflict between the working principle of enbpi and long-term forecasting?

**Comment by Valentin-Laurent** [comment]
Hello @Yulinwan. As discussed above, time series method implemented in MAPIE only allow 1-step forecasting. The way you can adapt to long-terme forecasting is to create a model that predicts at a given step-size. For ex, you can use a model that predicts 96 steps ahead, and then use MAPIE to measure uncertainty.
