### ISSUE TITLE
This video suggests there might be a bug in implementation due to coverage dropping for ICP

### ISSUE THREAD

**Issue by valeman** [scikit-learn-contrib/MAPIE#451]
https://www.youtube.com/watch?v=k6k_bUYyUNg&ab_channel=MLBoost

**Comment by thibaultcordier** [comment]
Thank you for sharing the video link which suggests a bug in the coverage validity. I have initiated a new issue that explains the reason for the bug as well as additional material that allows users to reproduce the bug.
