### ISSUE TITLE
Mathematical functions don't show up properly in generated notebooks in documentation

### ISSUE THREAD

**Issue by LacombeLouis** [scikit-learn-contrib/MAPIE#480]
**Is your documentation request related to a problem? Please describe.**
In the tutorials for documentation, when mathematical notation is used, it does not show up properly. 

![Screenshot 2024-07-05 at 11 01 31](https://github.com/scikit-learn-contrib/MAPIE/assets/63096108/cc76c176-388a-4516-b976-5a9669cf235c)

**Comment by Valentin-Laurent** [comment]
Comment for developers: the last PR (https://github.com/scikit-learn-contrib/MAPIE/pull/481) did not solve the issue, but make sure to check this attempt, it may be a step in the right direction (or the opposite).

Moreover, a LaTex related warning shows up when building the documentation, most probably related to this issue. When trying to solve the issue, easier to check if the warning disappears than to check the actual rendering in the doc.
