### ISSUE TITLE
EnbPI Prediction Intervals not centered correctly

### ISSUE THREAD

**Issue by jawharmohammed** [scikit-learn-contrib/MAPIE#495]
Hello MAPIE team, 

Congratulations on your excellent work! I have identified an error in the computation of the prediction intervals generated by EnbPI in MAPIE.

**Describe the bug**

The prediction intervals generated by the EnbPI method in MAPIE do not align with the expected behavior described in the pseudo code provided in the original paper.

**Expected behavior**

The prediction intervals should be centered at:
\[ 
f^{\Phi}_t(x_t) = \Phi \left(f^{\Phi}_i(x_t), i = 1, \ldots, T \right)
\]
![Expected Centering](https://github.com/user-attachments/assets/f146cf94-4ae0-435d-af5b-cd2b4fd133ed)

However, in the `predict` function of the `EnsembleRegressor` class, where the interval bounds are initialized, the bounds are set with the out-of-fold (oof) prediction of a single estimator rather than the aggregation of `y_pred_multi` as indicated in the pseudocode. This issue is highlighted in the following screenshot:

![Incorrect Initialization](https://github.com/user-attachments/assets/e734f0c3-5439-4d04-89fd-10e0f3f8827c)

**Suggested Solution**

A simple solution would be to replace this part with something like the following:

![Suggested Solution](https://github.com/user-attachments/assets/ef61d116-0b35-44de-b1a4-8a62c828a0bc)

Thank you for your attention to this matter!

**Comment by thibaultcordier** [comment]
Hello @jawharmohammed 

Thank you for your feedback and sorry for the late reply.
The bug you identified appears to be a bug (need more time to look into this). We've started discussing this with @vincentblot28 and will look into it further.

We'll get back to you shortly.

Best,
