### ISSUE TITLE
Problem when calculating SD

### ISSUE THREAD

**Issue by jvalegre** [scikit-learn-contrib/MAPIE#508]
**Describe the bug**
I run MAPIE three times using different alpha values (i.e. 0.05, 0.1 and 0.5). Then, I used the width of the resulting confidence intervals to calculate the corresponding standard deviations of the individual datapoints, using the equation:

`SD = √n * (upper limit - lower limit) / 2 * t`

using n as 1 since I calculated the SD for each individual point, and with Student's t values of 1.96, 1.645 and 0.674 for alphas 0.05, 0.1 and 0.5 respectively. I was expecting to have identical SDs when using the three alphas, but the differences are significant (i.e. for the first datapoint, SD of 0.45, 0.42 and 0.18 when changing alphas).

If this is not a bug, please could you help me understand why I get different SDs depending on the alpha used and suggest a preferred value of alpha to calculate the SD for individual points?

**To Reproduce**
These are all the MAPIE functions used:

```
    my_conformity_score = AbsoluteConformityScore()
    my_conformity_score.consistency_check = False
    mapie = MapieRegressor(loaded_model, method="plus", cv=-1, agg_function="median", conformity_score=my_conformity_score, n_jobs=-1, random_state=0)
    mapie.fit(X_train_scaled, y_train)
    y_pred, y_pis = mapie.predict(X_valid_scaled, alpha=[ALPHA])
```

**Expected behavior**
Identical SD for the same datapoint when using different alphas.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - MAPIE Version 0.8.6

**Comment by thibaultcordier** [comment]
Hello @jvalegre, to complete the explanation of @vincentblot28, see here a code snippet that reproduces the experiment you try to do (be free to change the assumption on the distribution of your residuals to see the difference).

```python
import numpy as np
from sklearn.linear_model import LinearRegression
from scipy import stats

from mapie.regression import MapieRegressor


n_samples = 1000

normal_assumption = True
uniform_assumption = not normal_assumption

# Generate data
X = np.random.normal(size=(n_samples, 1))
y = np.zeros(shape=(n_samples,))

# Generate test example
X_test = np.random.normal(size=(1, 1))

# Add noise to y according to the assumption (= distribution of the residuals)
if normal_assumption:
    eps = np.random.normal(size=(n_samples, ))
else:
    eps = np.random.uniform(low=-1, high=1, size=(n_samples, ))
y += eps

# Fit the model and predict
mapie_regressor = MapieRegressor(
    estimator=LinearRegression(), method="plus", cv=5, agg_function="median"
)
mapie_regressor.fit(X, y)

# Predict with different alpha values
alpha_list = np.linspace(0.1, 0.9, 9)
y_pred, y_pis = mapie_regressor.predict(X_test, alpha=alpha_list)

# Print the prediction intervals
length = y_pis[0, 1, :] - y_pis[0, 0, :]
print(length)

# Compute the theoretical length of the prediction intervals (under normal assumption)
k = n_samples
t = stats.t.ppf(1-alpha_list/2, df=k-1, loc=0, scale=1)
print(t)

# Compute the SD (calculus you propose)
print(length/(2*t))
```
