### ISSUE TITLE
Minor syntax issues in contribution guidelines

### ISSUE THREAD

**Issue by MischaDy** [scikit-learn-contrib/MAPIE#525]
**Describe the bug**
There are a handful of syntax issues in the contribution guidelines, such as improperly formatted links.

**To Reproduce**
1. Go the [contribution guidelines](https://github.com/scikit-learn-contrib/MAPIE/blob/master/CONTRIBUTING.rst)
2. Scroll down to e.g. "What to work on?" or "Documenting your change"
3. Notice broken link formatting.

**Expected behavior**
Highlighted text leading to the specified URLs.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - MAPIE Version: 0.4 and later

**Comment by Valentin-Laurent** [comment]
Hello @MischaDy, thank you for reporting this. We're adding it to our backlog, but you're welcome to make a pull request if you want :)
