### ISSUE TITLE
Wrong warning in regression_coverage_score

### ISSUE THREAD

**Issue by gmartinonQM** [scikit-learn-contrib/MAPIE#547]
The line : https://github.com/scikit-learn-contrib/MAPIE/blob/87c6f0eb8e700b4f2333cae59fbf34d237e5adeb/mapie/metrics.py#L58

should be deleted for two reasons : 

1. The order of the arguments is wrong : y_pred_low should come first
2. This trigger the warning all the time, since with any non-zero alpha, it is 100% sure that at least one `y_true` will be outside the confidence interval

Steps to reproduce:

```python
regression_coverage_score(y_true=[1], y_pred_low=[2], y_pred_up=[3])
```

**Comment by jawadhussein462** [comment]
Hi @gmartinonQM ,

Thank you for pointing this out and providing detailed reasoning. We will review this issue and get back to you as soon as possible.

Best regards,
