### ISSUE TITLE
Inconsistent functions: get_conformity_scores and get_estimation_distribution

### ISSUE THREAD

**Issue by ferpapi-clear** [scikit-learn-contrib/MAPIE#557]
**Describe the bug**
When using `MapieRegressor` to calculate uncertainty intervals, I came across this error:

```
The two functions get_conformity_scores and get_estimation_distribution of the ConformityScore class are not consistent. 
The following equation must be verified: self.get_estimation_distribution(X, y_pred, self.get_conformity_scores(X, y, y_pred)) == y
The maximum conformity score is 1.4319084584712982e-08.
The eps attribute may need to be increased if you are sure that the two methods are consistent.
````

I'm using MAPIE for time series forecasting.

I've tried the solution described here: https://github.com/scikit-learn-contrib/MAPIE/issues/321

But then I face another error:

`ValueError: Beta optimisation cannot be used with symmetrical conformity score function.`

**To Reproduce**
This is how I have setup MAPIE to calculate uncertainty intervals:

```python

self.cv_mapiets = BlockBootstrap(n_resamplings=30, n_blocks=10, overlapping=False)
self.mapie_enbpi = MapieTimeSeriesRegressor(
    model, 
    method="enbpi", 
    cv=self.cv_mapiets, 
    agg_function="mean", 
    n_jobs=-1
)
```

It's very similar to the setup used in the [time series tutorial](https://mapie.readthedocs.io/en/stable/examples_regression/4-tutorials/plot_ts-tutorial.html), but **I'm using the same data for training and validation** due to not having large individual time-series (normally 3 to 7 years of daily data, forecasting 1 year ahead). I don't think I can dispose of more recent data to be used for validation

**Expected behavior**
Getting intervals without errors

**Desktop (please complete the following information):**
 - MAPIE Version: 0.8.0
 
 Any help or suggestion is very much appreciated :)
Thanks for the awesome work!

**Comment by thibaultcordier** [comment]
Hello @ferpapi-clear, thank you for reporting this issue.

## Explanation of this exception

In your situation, the exception tells us that you are trying to use beta optimisation with a symmetrical conformity score. By default,  you are using the `AbsoluteConformityScore`, instanticated with `sym=True`. This is the cause of your problem.

## Resolution of the exception

If you want to use beta optimisation, you need an asymmetrical conformity score. You can do this with the following code:

```python
from mapie.conformity_score import AbsoluteConformityScore

my_conformity_score = AbsoluteConformityScore(sym=False)
my_conformity_score.consistency_check = False

mapie = MapieRegressor(model, cv=cv_mapiets, conformity_score=my_conformity_score)
```

## Conclusion

I hope I've been able to help you solve your problem. If you haven't used the beta optimisation, please share the full code (with toy datasets) with us to make sure we can reproduce your error. Please let me know if the solution works for you.

**Comment by ferpapi-clear** [comment]
Yeah, it seems to work! Thank you very much, and again, thanks for your work on this package :)
