### ISSUE TITLE
[ENHANCEMENT] Conformalized quantile regression

### ISSUE THREAD

**Issue by gmartinonQM** [scikit-learn-contrib/MAPIE#73]
As described in section 2.2 of this tutorial:
http://people.eecs.berkeley.edu/~angelopoulos/publications/downloads/gentle_intro_conformal_dfuq.pdf

**Comment by tvdaal** [comment]
Would be very useful to add, see also the descriptions here: https://towardsdatascience.com/how-to-predict-risk-proportional-intervals-with-conformal-quantile-regression-175775840dc4.

**Comment by RudrakshTuwani** [comment]
Hey @gmartinonQM , I can take this up if nobody else is working on it! 

I guess we should implement a new class for this as even though technically we are still creating prediction sets for regression, we need a different class of estimators (quantile prediction) and would probably need to specify `alpha` as part of `__init__`.

**Comment by gmartinonQM** [comment]
With great pleasure @RudrakshTuwani ! Yes a new class in a separate file `quantile_regression.py` would be perfect

**Comment by nilslacroix** [comment]
Are there still plans to implement this?

**Comment by vtaquet** [comment]
Conformalized QR as proposed by Romano et al. (2019) was implemented in PR #167 .
