### ISSUE TITLE
[DOCUMENTATION] Fix errors in code examples in tutorial section of documentation

### ISSUE THREAD

**Issue by AdirthaBorgohain** [scikit-learn-contrib/MAPIE#87]
**Is your documentation request related to a problem? Please describe.**
I found this library interesting and was going through the library code examples where I found a code error in the plotting of interval widths for the section "Estimating the uncertainty with different sklearn-compatible regressors". It uses a variable y_preds which is not defined earlier anywhere in the code. Besides, a few import statements are missing from sklearn methods, I have made the changes. Should I send a PR for the same?

**Describe the solution you'd like**
The incorrect line of code can be fixed by using y_pis instead of undefined y_preds and using the correct dimensions for the data. The import statements for the missing sklearn methods can be added as well.

**Comment by vtaquet** [comment]
Hi Adirtha, thanks for spotting these errors in the documentation ! Feel free to submit a PR fixing these to the master branch with myself or gmartinon as a reviewer. 

Thanks !

**Comment by AdirthaBorgohain** [comment]
Thank Vianney, I have added a PR for the issue.  Have mentioned you in the comments.

Thanks!
